spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: Password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     ddl-auto: create
    show-sql: true
    properties:
     hibernate:
       format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


