spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pfe_db
    username: postgres
    password: pgpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
